Page/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Home, name='Home'),
]

Start/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path, include
from django.contrib.auth import views
from django.contrib.auth.views import LogoutView
from django.contrib.auth.views import LoginView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', views.LoginView.as_view(), name='login'),
    url(r'^accounts/logout/$', views.LogoutView.as_view(), name='logout', kwargs={'next_page': ''}),
    path('administration/', include('administration.urls')),
    path('', include('Page.urls')),
]

administration/urls.py
from django.urls import path
from . import views
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path, include
urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('order/new/', views.neworder, name='neworder'),
    path('order/list/', views.listorder, name='listorder'),
    path('order/pending/', views.pendingorders, name='pendingorders'),
    path('order/edit/<int:pk>', views.editorder, name='editorder'),
    path('order/delete/<int:pk>', views.deleteorder, name='deleteorder'),
    path('order/active/<int:pk>', views.activeorder, name='activeorder'),
    path('service/add/<int:pk>', views.addservice, name='addservice'),
    path('service/new/<int:pk>', views.newservice, name='newservice'),
    path('service/list/', views.listservice, name='listservice'),
    path('services/list/', views.listservices, name='listservices'),
    path('services/edit/<int:pk>', views.editservices, name='editservices'),
    path('service/edit/<int:pk>', views.editservice, name='editservice'),
    path('service/delete/<int:pk>', views.deleteservice, name='deleteservice'),
    path('services/delete/<int:pk>', views.deleteservices, name='deleteservices'),
    path('employee/new/', views.new_employee, name='new_employee'),

    
    ]

administration/models.py
from django.db import models
from django.contrib import admin
from django.utils import timezone

class Order(models.Model):
    Names  =   models.CharField(max_length=70)
    Last_names = models.CharField(max_length=70)
    Phone = models.CharField(max_length=50)
    Address = models.CharField(max_length=200)
    Reference = models.CharField(max_length=200,blank=True, null=True)
    states = (
    	('inactive', 'Inactive'),
	    ('check', 'Check'),
	    ('active', 'Active'),
	    ('complete', 'Complete'),
	    )
    State = models.CharField(
	    max_length=10,
	    choices=states,
	    default='check',
	    )
    Description =  models.CharField(max_length=200,blank=True, null=True)
    Note =  models.CharField(max_length=200,blank=True, null=True)
    Create = models.DateTimeField(default=timezone.now,blank=True, null=True)
    def __str__(self):
        return self.Names

class Type(models.Model):
    Name = models.CharField(max_length=50,unique=True)
    Descripcion = models.CharField(max_length=200)
    color = models.CharField(max_length=50,blank=True, null=True)
    Create = models.DateTimeField(blank=True, null=True)
    def publish(self):
    	self.Create = timezone.now()
    	self.save()
    def __str__(self):
        return '%s' % (self.Name)

class Service(models.Model):
	Order = models.ForeignKey(Order, on_delete=models.CASCADE)
	Type = models.ForeignKey(Type, on_delete=models.CASCADE)
	Description =  models.CharField(max_length=200)
	Note =  models.CharField(max_length=200,blank=True, null=True)
	states = (
		('Inactive', 'Inactive'),
		('Active', 'Active'),
		)
	State = models.CharField(
		max_length=10,
		choices=states,
		default='Active',
		)
	Create = models.DateTimeField(default=timezone.now,blank=True, null=True)
	def __str__(self):
		return '%s %s' % (self.Order, self.Type)
	class Meta:
		unique_together = (("Order", "Type"),)

class Profile(models.Model):
	Names  =   models.CharField(max_length=70)
	Last_names = models.CharField(max_length=70)
	IdPersonal = models.CharField(max_length=50)
	Phone = models.CharField(max_length=50)
	Address = models.CharField(max_length=200)
	Start_Work = models.DateTimeField(blank=True, null=True)
	states = (
		('inactive', 'Inactive'),
		('active', 'Active'),
		('register', 'register'),
		)
	State = models.CharField(
		max_length=10,
		choices=states,
		default='register',
		)
	Usuario = models.OneToOneField('auth.User', on_delete=models.CASCADE,blank=True, null=True)
	Create = models.DateTimeField(default=timezone.now,blank=True, null=True)
	Note =  models.CharField(max_length=200,blank=True, null=True)
	def __str__(self):
		return '%s %s' % (self.Names, self.Last_names)

class Assign(models.Model):
	Service = models.ForeignKey(Service, on_delete=models.CASCADE,blank=True, null=True)
	Start_date = models.DateTimeField(blank=True, null=True)
	End_date = models.DateTimeField(blank=True, null=True)
	Profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
	Create = models.DateTimeField(default=timezone.now,blank=True, null=True)
	Note =  models.CharField(max_length=200,blank=True, null=True)
	states = (
		('assing', 'assing'),
		('active', 'Active'),
		)
	State = models.CharField(
		max_length=10,
		choices=states,
		default='assing',
		)
	def __str__(self):
		return '%s %s' % (self.Job, self.Profile)

administration/views.py
from .forms import OrderForm,TypeForm,ServiceForm,ProfileForm
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.template import RequestContext, Template
from django.contrib.auth import models
from django.contrib.auth.models import User
from django.contrib.auth.models import Group
from django.contrib.auth.forms import UserCreationForm
from django.http import JsonResponse
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
from .models import Order,Type,Service,Profile,Assign
import datetime
import calendar
@login_required
def dashboard(request):
	icon = "pe-7s-graph icon-gradient bg-ripe-malin"
	title = "Dashboard"
	text = "Start here, you can check sumary of the sistem if you want you can push the review button."
	pos = "dashboard"
	breacum = []
	brea ={}
	brea["NAME"] = "Dashboard"
	brea["URL"] = "dashboard"
	brea["ICO"] = None
	brea["Active"] = True
	breacum.append(brea)
	brea ={}
	brea["NAME"] = "Home"
	brea["URL"] = "dashboard"
	brea["ICO"] = "pe-7s-home"
	brea["Active"] = None
	breacum.append(brea)
	today = datetime.datetime.now() 
	month = today.month 
	noorders=Order.objects.filter(State="active",Create__month = month).count()
	orders = Order.objects.filter(State="active")
	nopendingorders = Order.objects.filter(State="check").count()
	monts = [4,3,2,1,0]
	months = []
	for x in monts:
		m3 = {}
		m1 = int(2 - x)
		m2 = month+m1
		if(m2>12):
			m2=m2-12
		m3["month"] = calendar.month_name[m2]
		months.append(m3)
	Services = []
	Ser = Type.objects.all()
	Serv = []
	for s in Ser:
		p = {}
		p["service"] = s.Name
		Serv.append(p)
		for m in monts:
			se = {}
			se["service"] = s.Name
			se["color"] = s.color
			se["month"] = None
			se["Count"] = None
			m1 = int(2 - m)
			m2 = month+m1
			se["month"] = calendar.month_name[m2]
			se["Count"] = Service.objects.filter(Type=s,Create__month=m2).count()
			Services.append(se)
	return render(request, 'administration/dashboard.html',{'icon':icon,'title':title,'text':text,'pos':pos,'breacum':breacum,'noorders': noorders,'months':months,'Services':Services,'nopendingorders':nopendingorders,'Serv':Serv})
@login_required
def neworder(request):
	icon = "pe-7s-box2 icon-gradient bg-ripe-malin"
	title = "New Order"
	text = "Form of order, you can add only the order to check before."
	pos = "cnorder"
	breacum = []
	brea ={}
	brea["NAME"] = "New Order"
	brea["URL"] = "neworder"
	brea["ICO"] = None
	brea["Active"] = True
	breacum.append(brea)
	brea ={}
	brea["NAME"] = "Orders"
	brea["URL"] = "listorder"
	brea["ICO"] = "pe-7s-box2"
	brea["Active"] = None
	breacum.append(brea)
	errores=None
	mensajes=None
	button="New Order"
	if request.method == "POST":
		form = OrderForm(request.POST)
		if form.is_valid():
			post = form.save(commit=False)
			post.save()
			mensajes="It has been create successfully!!"
			form = OrderForm()
		else:
			errores="No se ha podido guardar revise los campos para continuar..."
	else:
		mensajes=None
		form = OrderForm()
	return render(request, 'administration/create_new_order.html', {'icon':icon,'title':title,'pos':pos,'text':text,'breacum':breacum,'button': button,'form': form,'mensajes': mensajes,'errores': errores})
@login_required
def listorder(request):
	icon = "pe-7s-albums icon-gradient bg-ripe-malin"
	title = "List Order"
	text = "List of order, you can update or delete the orders."
	pos = "lorder"
	breacum = []
	brea ={}
	brea["NAME"] = "List of Orders"
	brea["URL"] = "listorder"
	brea["ICO"] = None
	brea["Active"] = True
	breacum.append(brea)
	brea ={}
	brea["NAME"] = "Orders"
	brea["URL"] = "listorder"
	brea["ICO"] = "pe-7s-box2"
	brea["Active"] = None
	breacum.append(brea)
	orders = Order.objects.filter(State="active")
	try:
		mensajes = request.session['mensajes']
		del request.session['mensajes']
	except Exception as e:
		mensajes=None
	try:
		errores = request.session['errores']
		del request.session['errores']
	except Exception as e:
		errores=None
	return render(request, 'administration/list_order.html', {'icon':icon,'title':title,'pos':pos,'text':text,'breacum':breacum,'orders': orders,'mensajes': mensajes,'errores': errores})
@login_required
def pendingorders(request):
	orders=Order.objects.filter(State="check")
	return render(request, 'administration/list_order.html',{'orders': orders})
@login_required
def editorder(request, pk):
	errores=None
	mensajes=None
	button="Edit Order"
	order=Order.objects.get(pk=pk)
	if request.method == "POST":
		form = OrderForm(request.POST, instance=order)
		if form.is_valid():
			post = form.save(commit=False)
			post.save()
			request.session['mensajes']="It has been edited successfully!"
			return redirect('listorder')
		else:
			request.session['errores']="No se ha podido guardar revise los campos para continuar..."
	else:
		form = OrderForm(instance=order)
	return render(request, 'administration/create_new_order.html', {'button': button,'form': form})
@login_required
def deleteorder(request,pk):
	order=Order.objects.get(pk=pk)
	form = OrderForm(instance=order)
	post = form.save(commit=False)
	post.State = "inactive"
	post.save()
	request.session['mensajes']="The order has been Delete successfully"
	return redirect('listorder')
@login_required
def activeorder(request,pk):
	order=Order.objects.get(pk=pk)
	form = OrderForm(instance=order)
	post = form.save(commit=False)
	post.State = "active"
	post.save()
	request.session['mensajes']="The order has been active successfully"
	return redirect('addservice', pk=pk)
@login_required
def newservice(request, pk):
	errores=None
	mensajes=None
	types=None
	if request.method == "POST":
		form = TypeForm(request.POST)
		if form.is_valid():
			post = form.save(commit=False)
			post.color = request.POST["favcolor"]
			post.save()
			request.session['mensajes']="Se ha guardado con exito!"
			form = TypeForm()
		else:
			request.session['errores']="The type of service has been create before..."
	else:
		form = TypeForm()
		types=Type.objects.all()
	return redirect('addservice',pk=pk)
@login_required
def addservice(request, pk):
	try:
		mensajes = request.session['mensajes']
		del request.session['mensajes']
	except Exception as e:
		mensajes=None
	try:
		errores = request.session['errores']
		del request.session['errores']
	except Exception as e:
		errores=None
	types=None
	order=Order.objects.get(pk=pk)
	types=Type.objects.all()
	if request.method == "POST":
		try:
			for service in request.POST.getlist('Services'):
				form1 = ServiceForm(request.POST)
				if form1.is_valid():
					post = form1.save(commit=False)
					post.Order=order
					post.Type=Type.objects.get(Name=service)
					post.save()
					mensajes = "It has been saved successfully!"
				else:
					errores="It has NOT been saved successfully..."
		except Exception as e:
			errores="The type of service has been assign before..."
		
		form = TypeForm()
		form1 = ServiceForm()
	else:
		form = TypeForm()
		form1 = ServiceForm()
	return render(request, 'administration/add_services.html', {'order':order,'form': form,'form1': form1,'mensajes': mensajes,'errores': errores,'types': types})

@login_required
def listservice(request):
	try:
		mensajes = request.session['mensajes']
		del request.session['mensajes']
	except Exception as e:
		mensajes=None
	try:
		errores = request.session['errores']
		del request.session['errores']
	except Exception as e:
		errores=None
	Services = Service.objects.filter(State="Active")
	return render(request, 'administration/list_service.html', {'Services': Services,'mensajes': mensajes,'errores': errores,})
@login_required
def listservices(request):
	try:
		mensajes = request.session['mensajes']
		del request.session['mensajes']
	except Exception as e:
		mensajes=None
	try:
		errores = request.session['errores']
		del request.session['errores']
	except Exception as e:
		errores=None
	Services = []
	Orders=Order.objects.filter(State="active")
	for x in Orders:
		Serv = {}
		Serv['pk']=x.pk
		Serv['Order']=str(x.pk) + "-" + x.Names + " " + x.Last_names
		types=Service.objects.filter(Order=x)
		tp=" "
		for y in types:
			tp=tp+" " + str(y.Type)
			Serv['Description']=str(y.Description)
			Serv['Note']=str(y.Note)
			Serv['Create']=y.Create
		Serv['Type']=tp
		Services.append(Serv)
	return render(request, 'administration/list_services.html', {'Services': Services,'mensajes': mensajes,'errores': errores,})
@login_required
def editservice(request, pk):
	Services=Service.objects.get(pk=pk)
	if request.method == "POST":
		form = ServiceForm(request.POST, instance=Services)
		if form.is_valid():
			post = form.save(commit=False)
			post.save()
			request.session['mensajes']="It has been edited successfully!"
			return redirect('listservice')
		else:
			request.session['errores']="No se ha podido guardar revise los campos para continuar..."
	else:
		form1 = ServiceForm(instance=Services)
	return render(request, 'administration/editservice.html', {'Services':Services,'form1':form1})
@login_required
def editservices(request, pk):
	try:
		mensajes = request.session['mensajes']
		del request.session['mensajes']
	except Exception as e:
		mensajes=None
	try:
		errores = request.session['errores']
		del request.session['errores']
	except Exception as e:
		errores=None
	errores=None
	mensajes=None
	types=None
	order=Order.objects.get(pk=pk)
	typess=Type.objects.all()
	Services=Service.objects.filter(Order=order)
	types = []
	for x in typess:
		t = {}
		t['pk'] = x.pk
		t['Name'] = x.Name
		for y in Services:
			if y.Type==x:
				t['op'] = '1'
		types.append(t)
	if request.method == "POST":
		for serv in Services:
			serv.delete()
		servicelist = request.POST.getlist('Services')
		for service in servicelist:
			tp = Type.objects.get(Name=service)
			form1 = ServiceForm(request.POST)
			if form1.is_valid():

administration/templates/administration/add_services.html
 {% extends 'administration/base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'administration/multi/css/bootstrap-select.css' %}">
<link rel="stylesheet" href="{% static 'administration/notify/dist/css/Lobibox.min.css' %}"/>

<script type="text/javascript">
    window.onload = function() {
    {% if mensajes %}
        Lobibox.notify('success', {
                    showClass: 'zoomInUp',
                    hideClass: 'zoomOutDown',
                    delay: 15000,
                    msg: '{{mensajes}}'
                });     

     {% endif %}
    {% if errores %}
    Lobibox.notify('error', {
                    showClass: 'zoomInUp',
                    hideClass: 'zoomOutDown',
                    delay: 15000,
                    msg: '{{errores}}'
                });
    {% endif %}
    
};
</script>



<div class="jumbotron">
  <center><h1>Add services</h1>
    <p class="mb-4">List of services, you can add more services below</p></center>

<form method="POST" class="post-form" action="{% url 'newservice' pk=order.pk%}">

      {% csrf_token %}
       {% for non_field_error in form.non_field.errors %}
      <help class="is-danger">{{ non_field_error}}</help>
       {% endfor %}
    
    <div class="form-group">
         <div class="row">
      <div class="col-sm-2"></div>
      <div class="col-sm-2"></div>
      <label class="col-sm-2 col-form-label"><i class="fa fa-address-book"></i> Add type of services</label>
      
      <div class="col-sm-2">
      {{form.Name}}
      </div>
      </div>

    </div>
 <div class="form-group">
         <div class="row">
      <div class="col-sm-2"></div>
      <div class="col-sm-2"></div>
      <label class="col-sm-2 col-form-label"><i class="fa fa-address-book"></i> Add description</label>
      
      <div class="col-sm-2">
        {{form.Descripcion}}
      </div>
      </div>

    </div>

 <div class="form-group">
         <div class="row">
      <div class="col-sm-2"></div>
      <div class="col-sm-2"></div>
      <label class="col-sm-2 col-form-label"><i class="fa fa-address-book"></i> Color</label>
      
      <div class="col-sm-2">
        <input type="color" name="favcolor" class="form-control" value="#ff0000">
      </div>
      </div>

    </div>


        <center>
        <button type="submit" class="btn btn-primary"> <i class="fa fa-check"></i> New type</button>
        </center> 
  </form>

</div>




<div class="container">
            
<div class="row" >
  <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-10">
 
 <form method="POST" class="post-form" style="color: rgb(133, 135, 150); background: rgb(234, 236, 244  );">

    {% csrf_token %}
     {% for non_field_error in form1.non_field.errors %}
    <help class="is-danger">{{ non_field_error}}</help>
     {% endfor %} 
      <div class="form-group row">

    <label class="col-sm-2 col-form-label"><i class="fa fa-address-book"></i> Order</label>
    <div class="col-sm-4">
     
    <input type="text" class="form-control form-control-user" id="exampleInputEmail" aria-describedby="emailHelp" value="{{order.pk}}" readonly="false" style="text-align: center;">
                   
    </div>
    <label class="col-sm-2 col-form-label"><i class="fa fa-address-book"></i> Names</label>
    <div class="col-sm-4">
     
    <input type="text" class="form-control form-control-user" id="exampleInputEmail" aria-describedby="emailHelp" value="{{order.Names}} {{order.Last_names}}" readonly="false" style="text-align: center;">
                   
    </div>

  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label"><i class="fa fa-address-book"></i> Services</label>
    <div class="col-sm-10">
        <select multiple class="selectpicker form-control" id="number-multiple" data-container="body" data-live-search="true" title="Select services" data-hide-disabled="true" data-actions-box="true" data-virtual-scroll="false" name="Services"></select>
      </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label"><i class="fa fa-mobile"></i> Description</label>
    <div class="col-sm-10">
      {{form1.Description}}
    </div>
  </div>  
  <div class="form-group row">
    <label class="col-sm-2 col-form-label"><i class="fa fa-book"></i> Note</label>
    <div class="col-sm-10">
      {{form1.Note}}
    </div>
  </div>
   <center>
      <button type="submit" class="btn btn-primary"> <i class="fa fa-check"></i> Add services</button>
      </center>
</form>

  </div>  
</div>

</div>


  





<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.bundle.min.js"></script>


<script src="{% static 'administration/multi/js/bootstrap-select.js' %}"></script>

  <script src="{% static 'administration/notify/dist/js/Lobibox.min.js' %}"></script>
<script>
function createOptions(number) {
  var options = [], _options;

 {% for type in types %}
    {%if type.op == '1' %}
    var option = '<option selected value="' + "{{type.Name}}" + '">' + "{{type.Name}}" + '</option>';
    options.push(option);
    {%else%}
    var option = '<option value="' + "{{type.Name}}" + '">' + "{{type.Name}}" + '</option>';
    options.push(option);
    {% endif %}
  {%endfor%}

  _options = options.join('');
  

  $('#number-multiple')[0].innerHTML = _options;
}

var mySelect = $('#first-disabled2');

createOptions(4);

</script>

{% endblock %}

administration/templates/administration/create_new_job.html
 {% extends 'administration/base.html' %}
{% block content %}
{% load static %}


<link rel="stylesheet" href="{% static 'administration/notify/dist/css/Lobibox.min.css' %}"/>
<link rel="stylesheet" href="{% static 'administration/date/css/bootstrap-datetimepicker.min.css' %}"/>

<script src="{% static 'administration/date/js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'administration/date/js/moment-with-locales.min.js' %}"></script>


<script type="text/javascript">
    window.onload = function() {
    {% if mensajes %}
        Lobibox.notify('success', {
                    showClass: 'zoomInUp',
                    hideClass: 'zoomOutDown',
                    delay: 15000,
                    msg: '{{mensajes}}'
                });     

     {% endif %}
    {% if errores %}
    Lobibox.notify('error', {
                    showClass: 'zoomInUp',
                    hideClass: 'zoomOutDown',
                    delay: 15000,
                    msg: '{{errores}}'
                });
    {% endif %}
    
};
</script>


<div class="jumbotron">
  <center><h1>Add new employee</h1></center>

</div>
<div class="container">




     <center>          
<div class="row" >
  <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-10">
 
 <form method="POST" class="post-form" style="color: rgb(133, 135, 150); background: rgb(234, 236, 244  );">

    {% csrf_token %}
     {% for non_field_error in form.non_field.errors %}
    <help class="is-danger">{{ non_field_error}}</help>
     {% endfor %} 
      <div class="form-group row">

    <label class="col-sm-2 col-form-label"><i class="fa fa-address-book"></i> Names:</label>
    <div class="col-sm-10">
      {{form.Names}}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label"><i class="fa fa-address-card"></i> Last Names:</label>
    <div class="col-sm-10">
      {{form.Last_names}}
    </div>
  </div>
   <div class="form-group row">
    <label class="col-sm-2 col-form-label"><i class="fa fa-id-card"></i> Id:</label>
    <div class="col-sm-10">
      {{form.IdPersonal}}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label"><i class="fa fa-mobile"></i> Phone:</label>
    <div class="col-sm-10">
     {{form.Phone}}
    </div>
  </div>
   <div class="form-group row">
    <label class="col-sm-2 col-form-label"><i class="fa fa-address-card"></i> Address:</label>
    <div class="col-sm-10">
      {{form.Address}}
    </div>
  </div>
   <div class="form-group row">
    <label class="col-sm-2 col-form-label"><i class="fa fa-bookmark"></i> Star work:</label>
    <div class="col-sm-10">
            <div class="input-group mb-6">
               {{form.Start_Work}}
                <div class="input-group-append">
                  <button class="btn btn-outline-secondary" type="button" id="button-addon2" onclick="hacer_click()"> <i class="far fa-calendar-alt"></i></button>
                </div>
              </div>
      
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label"><i class="fa fa-book"></i> Note:</label>
    <div class="col-sm-10">
      {{form.Note}}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label"><i class="fa fa-users"></i> User:</label>
    <div class="col-sm-10">
      <input type="text" name="user" class= "form-control" placeholder= "Put the username">
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-10">
      <center>
      <button type="submit" class="btn btn-primary"> <i class="fa fa-check"></i> {{button}}</button>
      </center>
    </div>
  </div>

</form>

  </div>  
</div>
</center> 
</div>

  <script type="text/javascript">
            function hacer_click()
    { 
        $("#id_Start_Work").focus();
    }

            $(function () {

            $('#id_Start_Work').datetimepicker({
            "allowInputToggle": true,
            "showClose": true,
            "showClear": true,
            "showTodayButton": true,
            "format": "YYYY-MM-DD",
            });
            });
        </script>
<!-- Bootstrap core JavaScript-->
    <script src="{% static 'administration/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'administration/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Page level plugins -->
  <script src="{% static 'administration/vendor/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'administration/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

  <!-- Page level custom scripts -->
  <script src="{% static 'administration/js/demo/datatables-demo.js' %}"></script>

  <script src="{% static 'administration/notify/dist/js/Lobibox.min.js' %}"></script>
 <script src="{% static 'administration/date/js/bootstrap-datetimepicker.min.js' %}"></script>


{% endblock %}

administration/templates/administration/vacio.html
 {% extends 'administration/base.html' %}
{% block content %}
{% load static %}
{% endblock %}